name: cercasco
description: Aplicación móvil para el casco inteligente Cercasco.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ==== Dependencias básicas ====
  cupertino_icons: ^1.0.6           # iconos estilo iOS
  http: ^1.2.2                      # comunicación con ESP32 vía HTTP
  flutter_colorpicker: ^1.0.3       # selector de color para control de LEDs
  shared_preferences: ^2.3.2        # guardar configuraciones y sesión localmente

  # ==== Firebase (para login/register, opcional por ahora) ====
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ==== Recursos (assets) ====
  assets:
    - assets/images/
    - assets/icons/
